---
- name: Update and upgrade apt packages
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: safe
        update_cache: yes
